/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Alvin' at '12/31/16 4:48 PM' with Gradle 2.14.1
 *
 * @author Alvin, @date 12/31/16 4:48 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
